"""empty message

Revision ID: 10a5892057bf
Revises: f2a239dcc9dc
Create Date: 2018-12-13 19:46:28.220381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a5892057bf'
down_revision = 'f2a239dcc9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('_todo', sa.Column('image_uri', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('_todo', 'image_uri')
    # ### end Alembic commands ###
