"""empty message

Revision ID: 9ed308625047
Revises: 10a5892057bf
Create Date: 2018-12-13 21:21:07.645303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed308625047'
down_revision = '10a5892057bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('_todo', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('_todo', 'is_hidden')
    # ### end Alembic commands ###
