"""empty message

Revision ID: f2a239dcc9dc
Revises: 11e82f25aefe
Create Date: 2018-12-13 16:04:01.908072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a239dcc9dc'
down_revision = '11e82f25aefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('_todo', sa.Column('creation_timestamp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('_todo', 'creation_timestamp')
    # ### end Alembic commands ###
